# Generated by Django 4.2 on 2023-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=255)),
                ('order_weight', models.PositiveIntegerField()),
                ('start_location', models.TextField()),
                ('finished_location', models.TextField()),
                ('delivery_fee', models.PositiveIntegerField()),
                ('period', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
