# Generated by Django 4.2 on 2023-04-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_weight',
            field=models.FloatField(),
        ),
    ]
