# Generated by Django 4.2 on 2023-04-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='diff_times',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
