# Generated by Django 4.2 on 2023-04-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_work_diff_times_work_fine_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
