# Generated by Django 4.2 on 2023-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_work_finish_time_alter_work_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_fee',
            field=models.IntegerField(),
        ),
    ]
