# Generated by Django 4.2 on 2023-05-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
